import pandas as pd
a=pd.Series([10,20,30,40,50])
b=pd.Series([40,50,60,70,80])
print("Series A:")
print(a)
print("Series B:")
print(b)
non_com=a[~a.isin(b)].tolist()+b[~b.isin(a)].tolist()
print("items not common to both:")
print(non_com)
print("the sum of series B is:",b.sum())
print("the average of series A is:",a.mean())
print("the median of series B is:",b.median())
print("the largest element in series A is:",a.max())
print("the smallest element in series A is:",a.min())

#aggregation functions
import numpy as np
d=np.array([4,2,3,7,9])
print("array:",d)
mini=d.min()
print("the minimum of the array is:",mini)
maxi=d.max()
print("the maximum element of the array is:",maxi)
sum=d.sum()
print("the sum of the array is:",sum)
imin=d.argmin()
print(imin)
imax=d.argmax()
print(imax)
stdv=d.std()
print("the standard deviation of the array is",stdv)
vari=d.var()
print("the variance of the array is",vari)
avg=d.mean()
print("the average of the array is",avg)